# -*- coding: utf-8 -*-
"""Assignment_2a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pLHAngw54Z_sSxBdGJ0DuCRD0DnIJNHV
"""

n=int(input("Enter number of terms: "))
a=0
b=1
print(0)
print(1)
for i in range (0,n-2):
  print(a+b)
  b=a+b
  a=b-a



