# -*- coding: utf-8 -*-
"""Assignment_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pLHAngw54Z_sSxBdGJ0DuCRD0DnIJNHV
"""

pip install scikit-learn

pip install matplotlib

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as num
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier
#from sklearn.cross_validation import train_test_split
# %matplotlib inline

from sklearn.model_selection import train_test_split

data=pd.read_csv('mnist_test.csv')
datatest=pd.read_csv('mnist_train.csv')

data.head()

datatest.head()

a=data.iloc[3,1:].values

a=a.reshape(28,28).astype('uint8')
plt.imshow(a)

b=datatest.iloc[3,1:].values

b=b.reshape(28,28).astype('uint8')
plt.imshow(b)

dtrain_x=data.iloc[:,1:]
dtrain_y=data.iloc[:,0]

x_train=dtrain_x
y_train=dtrain_y

dtest_x=datatest.iloc[:,1:]
dtest_y=datatest.iloc[:,0]

x_test=dtest_x
y_test=dtest_y

rf=RandomForestClassifier(n_estimators=100)

rf.fit(x_train,y_train)

pred=rf.predict(x_test)

pred

c=y_test.values

count=0
for i in range(len(pred)):
  if pred[i]==c[i]:
    count+=1

count

len(pred)

accuracy=(count/len(pred))*100
print("Accuracy is: ",accuracy,"%")