# -*- coding: utf-8 -*-
"""Assignment_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pLHAngw54Z_sSxBdGJ0DuCRD0DnIJNHV
"""

a=[]
b=[]
n=int(input("Enter number of elements in set1: "))
print("Enter elements in set 1")
for i in range (0,n):
  a.append(int(input()))
m=int(input("Enter number of elements in set2: "))
print("Enter elements in set 2")
for j in range (0,m):
  b.append(int(input()))

set1=set(a)
set2=set(b)
setu=set(a+b)
setd1=set1.difference(set2)
setd2=set2.difference(set1)
setsd=set1.symmetric_difference(set2)

print("Entered set 1: ",set1)
print("Entered set 2: ",set2)
print("Union of set 1 and set 2: ",setu)
print("Difference of set1 and set 2: ",setd1)
print("Difference of set2 and set 1: ",setd2)
print("Symmetric difference between set1 and set2: ",setsd)



