# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pLHAngw54Z_sSxBdGJ0DuCRD0DnIJNHV
"""

print("Hello World")

